from enum import Enum

class Game(Enum):
    rgby = "RED/GREEN/BLUE/YELLOW"
    gsc = "GOLD/SILVER/CRYSTAL"
    rse = "RUBY/SAPPHIRE/EMERALD"
    frlg = "FIRERED/LEAFGREEN"
    dp = "DIAMOND/PEARL"
    platinum = "PLATINUM"
    hgss = "HEARTGOLD/SOULSILVER"
    bw = "BLACK/WHITE"
    b2w2 = "BLACK 2/WHITE 2"
    xy = "X/Y"
    oras = "OMEGA RUBY/ALPHA SAPPHIRE"
    sm = "SUN/MOON"
    usum = "ULTRA SUN/ULTRA MOON"
    lgpe = "LET'S GO PIKACHU/LET'S GO EEVEE"
    swsh = "SWORD/SHIELD"
    bdsp = "BRILLIANT DIAMOND/SHINING PEARL"
    pla = "LEGENDS ARCEUS"
    sv = "SCARLET/VIOLET"
    za = "Z-A"
